### ISSUE TITLE
Save a list of the empty ticks per epoch, and expose them through an endpoint

### ISSUE THREAD

**Issue by LINCKODE** [qubic/go-archiver#60]

**Comment by sallymoc** [comment]
The ticket is needed to solve the issue https://github.com/qubic/explorer-frontend/issues/156 from the web explorer

**Comment by alexmf91** [comment]
Hey @sallymoc , @LINCKODE , @0xluk

After reviewing the requirements for deprecating the current TickOverview endpoint, I’ve come to the following conclusion:

Since the Archiver's latest stats endpoint doesn’t include the necessary tick data (which we currently fetch via TickOverview), it would be beneficial to introduce a dedicated endpoint for retrieving tick-related data.

Here’s the proposed structure for this new endpoint:
### Proposed Tick Data Endpoint

- **Endpoint: Get ticks with pagination**
    - **Parameters**:
        - **Page size**: The number of items to be retrieved per page.
        - **Page number**: The page to retrieve.
        
    - **Response**:
        - **data**: An array containing all result objects.
        - **Pagination details**:
            - `currentPage ` (number): Total number of available records.
            - `pageSize ` (number): Size of the page
            - `totalPages` (number): Total number of pages.
            - `totalItems` (number): Total number of available records.
            - `nextPage` (number | null): Page number or Link (then type will be string | null) to the next page, or `null` if on the last page.
            - `previousPage` (number | null): Page number or Link (then type will be string | null) to the previous page, or `null` if on the first page.

#### Current Tick Structure (from `TickOverview`):
Each tick in the response has this structure:
```json
{
    "tick": 16061392,
    "arbitrated": true
}
```
- If `arbitrated` is `true`, the tick is considered **incomplete**.

I think we can keep that structure for tick unless integration team thinks that we could improve it.


#### Example Response Structure:
```json
{
  "data": [
    {
        "tick": 16061392,
        "arbitrated": true
    },
    {
        "tick": 16061392,
        "arbitrated": true
    }
  ],
  "paginationInfo": {
    "currentPage": 1,
    "pageSize": 10,
    "totalPages": 100,
    "totalItems": 1000,
    "nextPage": 2,
    "previousPage": null
  }
}
```
